name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    paths-ignore:
      - ".github/**"
    types:
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

env:
  TZ: UTC

  COMPOSER_ALLOW_SUPERUSER: '1' # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
  COMPOSER_AUTH: '{"http-basic":{"repo.packagist.com":{"username":"token","password":"${{ secrets.PACKAGIST_AUTH_TOKEN }}"}}}'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-environment

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          extensions: ctype, iconv, intl
          ini-values: date.timezone=${{ env.TZ }}, memory_limit=-1, session.gc_probability=0
          tools: composer:v2, cs2pr, symfony

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - uses: actions/cache@v3
        with:
          path: ${{ env.COMPOSER_CACHE_DIR }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: symfony composer validate

      - run: symfony security:check

      - run: make setup@integration

      - run: symfony console cache:clear --env=dev

      - name: Run PHPStan
        run: symfony php bin/phpstan --no-progress

      - name: Validate database schema
        run: symfony console doctrine:schema:validate --skip-mapping -e test_cached

      - name: Run PHPUnit
        run: symfony php bin/phpunit --colors=always

      - run: symfony php bin/php-cs-fixer fix --verbose --diff --dry-run

  auto_merge_composer_operation:
    runs-on: ubuntu-latest
    needs: [ checks ]
    if: ${{ github.actor == 'yprox' && contains(github.event.pull_request.labels.*.name, 'bifrost:composer_operation') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: "${{ secrets.GH_MANALA_SYNC_TOKEN }}"
          MERGE_LABELS: "bifrost:composer_operation"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"
          MERGE_READY_STATE: "clean,has_hooks,unknown,unstable,blocked"

  auto_merge_dependabot:
    runs-on: ubuntu-latest
    needs: [checks]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.ACTION_DEPENDABOT_AUTO_MERGE_TOKEN }}
