name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"
  pull_request:
    paths-ignore:
      - ".github/**"
    types:
      - opened
      - reopened
      - synchronize
      - labeled

concurrency:
  cancel-in-progress: true
  group: ci-${{ github.ref }}

env:
  TZ: UTC
  PHP_VERSION: 7.4
  NODE_VERSION: 14

  COMPOSER_ALLOW_SUPERUSER: '1' # https://getcomposer.org/doc/03-cli.md#composer-allow-superuser
  COMPOSER_AUTH: '{"http-basic":{"repo.packagist.com":{"username":"token","password":"${{ secrets.PACKAGIST_AUTH_TOKEN }}"}}}'

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.PHP_VERSION }}
          coverage: none
          extensions: ctype, iconv, intl
          ini-values: date.timezone=${{ env.TZ }}, memory_limit=-1, session.gc_probability=0
          tools: composer:v2, cs2pr, symfony

      - run: symfony composer validate

      - run: symfony security:check

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--prefer-dist --optimize-autoloader --no-scripts"

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Get Yarn cache directory
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Cache Yarn dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.yarn-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install
      - run: yarn lint
      - run: yarn build

  auto_merge_composer_operation:
    runs-on: ubuntu-latest
    needs: [ checks ]
    if: ${{ github.actor == 'yprox' && contains(github.event.pull_request.labels.*.name, 'bifrost:composer_operation') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Merge pull requests
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: "${{ secrets.GH_MANALA_SYNC_TOKEN }}"
          MERGE_LABELS: "bifrost:composer_operation"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"

  auto_merge_dependabot:
    runs-on: ubuntu-latest
    needs: [checks]
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: ahmadnassri/action-dependabot-auto-merge@v2
        with:
          github-token: ${{ secrets.ACTION_DEPENDABOT_AUTO_MERGE_TOKEN }}
