{{- $has_mysql := .Vars.system.mysql.version -}}
{{- $has_redis := .Vars.system.redis.version -}}

# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk
include $(_ROOT_DIR)/.manala/make/git.mk

.DEFAULT_GOAL := help

user := $(shell id -u)
group := $(shell id -g)

dc := USER_ID=$(user) GROUP_ID=$(group) docker-compose
sail := ./vendor/bin/sail

HELP += $(call help_section, Environment)

HELP += $(call help,setup,             Setup the development environment)
setup: setup-laravel
	$(MAKE) up
	$(setup)
	@echo
	@$(call message_success, The development environment has been successfully set up.)
	@echo

HELP += $(call help,setup@integration, Setup the integration environment)
setup@integration: export APP_ENV=test
setup@integration: setup-symfony@integration
	$(MAKE) _up
	$(setup_integration)
	@echo
	@$(call message_success, The integration environment has been successfully set up.)
	@echo

setup-laravel:
	$(MAKE) setup-domain

setup-laravel@integration:
	$(symfony) server:ca:install

setup-domain:
	$(symfony) proxy:domain:attach {{ .Vars.system.app_name }}

_up:
	$(sail) up --detach

	{{ if or ($has_mysql) -}}
	@$(call message_warning, Waiting for the database to be ready...)
	@until docker inspect -f {{ "{{.State.Health.Status}}" }} `$(dc) ps -q {{ .Vars.system.app_name }}-mysql` | grep -q "healthy"; do \
      $(call message_warning, Waiting...); \
      sleep 1; \
	done
	@$(call message_success, The database is ready!)
	{{- end }}

HELP += $(call help,up,                Start the development environment)
up:
	$(MAKE) _up
	@echo

HELP += $(call help,halt,              Stop the development environment)
halt:
	$(sail) stop

HELP += $(call help,destroy,           Destroy the development environment)
destroy: halt
	$(sail) down --volumes
	@echo
	@$(call message_error, ALL CONTAINERS HAVE BEEN DESTROYED)
	@echo

HELP += $(call help_section, Project)
