{{- with .Vars.system -}}
.SILENT:

-include .manala/Makefile

define setup
    $(MAKE) install-app
    $(MAKE) init-db@test
endef

define setup_integration
    $(MAKE) install-app@integration
endef

###########
# Install #
###########

## Install application
install-app: composer-install init-db
install-app:
	$(php) bin/console cache:clear
	yarn install
	yarn dev

## Install application in integration environment
install-app@integration: export APP_ENV=test
install-app@integration:
	$(composer) install --ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader
	yarn install --color=always --no-progress --frozen-lockfile
	yarn dev
	$(MAKE) init-db@integration

################
# Common tasks #
################

composer-install:
	$(composer) install --ansi --no-interaction

init-db:
	$(php) bin/console doctrine:database:drop --force --if-exists --no-interaction
	$(php) bin/console doctrine:database:create --no-interaction
	$(php) bin/console doctrine:schema:update --force --no-interaction # to remove when we will use migrations
	# $(php) bin/console doctrine:migrations:migrate --no-interaction
	$(php) bin/console hautelook:fixtures:load --no-interaction

init-db@test: export APP_ENV=test
init-db@test: init-db

init-db@integration: export APP_ENV=test
init-db@integration:
	$(php) bin/console doctrine:database:create --if-not-exists --no-interaction
	$(php) bin/console doctrine:schema:update --force --no-interaction # to remove when we will use migrations
	# $(php) bin/console doctrine:migrations:migrate --no-interaction
	$(php) bin/console hautelook:fixtures:load --no-interaction

reload-db@test: export APP_ENV=test
reload-db@test:
	$(php) bin/console hautelook:fixtures:load --purge-with-truncate --no-interaction

{{- end }}
