{{- with .Vars.system -}}
.SILENT:

-include .manala/Makefile

define setup
    $(call log_and_call, $(MAKE) install-app)
    $(call log_and_call, $(MAKE) init-db@test)
endef

define setup_integration
    $(call log_and_call, $(MAKE) install-app@integration)
endef

###########
# Install #
###########

## Install application
install-app: composer-install init-db
install-app:
	$(call log_and_call, $(php) bin/console cache:clear)
	$(call log_and_call, yarn install)
	$(call log_and_call, yarn dev)

## Install application in integration environment
install-app@integration: export APP_ENV=test
install-app@integration:
	$(call log_and_call, $(composer) install --ansi --no-interaction --no-progress --prefer-dist --optimize-autoloader)
	$(call log_and_call, yarn install --color=always --no-progress --frozen-lockfile)
	$(call log_and_call, yarn dev)
	$(call log_and_call, $(MAKE) init-db@integration)

################
# Common tasks #
################

composer-install:
	$(call log_and_call, $(composer) install --ansi --no-interaction)

init-db:
	$(call log_and_call, $(php) bin/console doctrine:database:drop --force --if-exists --no-interaction)
	$(call log_and_call, $(php) bin/console doctrine:database:create --no-interaction)
	$(call log_and_call, $(php) bin/console doctrine:schema:update --force --no-interaction) # to remove when we will use migrations
	# $(php) bin/console doctrine:migrations:migrate --no-interaction
	$(call log_and_call, $(php) bin/console hautelook:fixtures:load --no-interaction)

init-db@test: export APP_ENV=test
init-db@test: init-db

init-db@integration: export APP_ENV=test
init-db@integration:
	$(call log_and_call, $(php) bin/console doctrine:database:create --if-not-exists --no-interaction)
	$(call log_and_call, $(php) bin/console doctrine:schema:update --force --no-interaction) # to remove when we will use migrations
	# $(php) bin/console doctrine:migrations:migrate --no-interaction
	$(call log_and_call, $(php) bin/console hautelook:fixtures:load --no-interaction)

reload-db@test: export APP_ENV=test
reload-db@test:
	$(call log_and_call, $(php) bin/console hautelook:fixtures:load --purge-with-truncate --no-interaction)

{{- end }}
