# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk
include $(_ROOT_DIR)/.manala/make/git.mk

.DEFAULT_GOAL := help

user := $(shell id -u)
group := $(shell id -g)

dc := USER_ID=$(user) GROUP_ID=$(group) docker-compose
symfony := symfony
php := $(symfony) php
composer := $(symfony) composer

HELP += $(call help,setup,             Setup the development environment)
setup: setup-symfony build-docker
	$(call log_and_call, $(dc) up --detach)
	$(call log_and_call, $(setup))
	echo
	$(call message_success, The development environment has been successfully set up.)
	echo

HELP += $(call help,setup@integration, Setup the integration environment)
setup@integration: export APP_ENV=test
setup@integration: setup-symfony@integration build-docker
	$(call log_and_call, $(dc) up --detach)
	$(call log_and_call, $(setup_integration))
	echo
	$(call message_success, The integration environment has been successfully set up.)
	echo

setup-symfony:
	$(call log_and_call, $(symfony) server:ca:install)
	$(call log_and_call, $(symfony) proxy:start)
	$(call log_and_call, $(symfony) proxy:domain:attach {{ .Vars.system.app_name }})

setup-symfony@integration:
	$(call log_and_call, $(symfony) server:ca:install)

build-docker:
	$(call log_and_call, mkdir -p $(_ROOT_DIR)/.manala/.docker/db-data)
	$(call log_and_call, mkdir -p $(_ROOT_DIR)/.manala/.docker/db-data-test)
	$(call log_and_call, mkdir -p $(_ROOT_DIR)/.manala/.docker/redis-data)
	$(call log_and_call, mkdir -p $(_ROOT_DIR)/.manala/.docker/redis-data-test)
	$(call log_and_call, $(dc) build)

HELP += $(call help,up,                Start the development environment)
up:
	$(call log_and_call, $(dc) up --detach)
	echo
	$(call message_success, You can now run the Symfony server)
	echo

HELP += $(call help,halt,              Stop the development environment)
halt:
	$(call log_and_call, $(dc) down)

HELP += $(call help,destroy,           Destroy the development environment)
destroy: halt
	$(call log_and_call, $(dc) rm --force)
	echo
	$(call message_error, ALL CONTAINERS HAVE BEEN DESTROYED)
	echo
