# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk
include $(_ROOT_DIR)/.manala/make/git.mk

.DEFAULT_GOAL := help

user := $(shell id -u)
group := $(shell id -g)

dc := USER_ID=$(user) GROUP_ID=$(group) docker-compose
symfony := symfony
php := $(symfony) php
composer := $(symfony) composer

HELP += $(call help_section, Environment)

HELP += $(call help,setup,             Setup the development environment)
setup: setup-symfony
	$(dc) build
	$(dc) up --detach
	$(setup)
	@echo
	@$(call message_success, The development environment has been successfully set up.)
	@echo

HELP += $(call help,setup@integration, Setup the integration environment)
setup@integration: export APP_ENV=test
setup@integration: setup-symfony@integration
	$(dc) build
	$(dc) up --detach
	$(setup_integration)
	@echo
	@$(call message_success, The integration environment has been successfully set up.)
	@echo

setup-symfony:
	$(symfony) server:ca:install
	$(symfony) proxy:start
	$(symfony) proxy:domain:attach {{ .Vars.system.app_name }}

setup-symfony@integration:
	$(symfony) server:ca:install

HELP += $(call help,up,                Start the development environment)
up:
	$(dc) up --detach
	@echo
	@$(call message_success, You can now run the Symfony server)
	@echo

HELP += $(call help,halt,              Stop the development environment)
halt:
	$(dc) stop

HELP += $(call help,destroy,           Destroy the development environment)
destroy: halt
	$(dc) down --volumes
	@echo
	@$(call message_error, ALL CONTAINERS HAVE BEEN DESTROYED)
	@echo

HELP += $(call help_section, Project)
