# Relative root dir ("."|".."|"../.."|…)
_ROOT_DIR := $(patsubst ./%,%,$(patsubst %/.manala/Makefile,%,./$(filter %.manala/Makefile,$(MAKEFILE_LIST))))
# Is current dir root ? (""|"1")
_ROOT := $(if $(filter .,$(_ROOT_DIR)),1)
# Relative current dir ("."|"foo"|"foo/bar"|…)
_DIR := $(patsubst ./%,%,.$(patsubst $(realpath $(CURDIR)/$(_ROOT_DIR))%,%,$(CURDIR)))

include $(_ROOT_DIR)/.manala/make/text.mk
include $(_ROOT_DIR)/.manala/make/help.mk
include $(_ROOT_DIR)/.manala/make/os.mk
include $(_ROOT_DIR)/.manala/make/git.mk

.DEFAULT_GOAL := help

user := $(shell id -u)
group := $(shell id -g)

dc := USER_ID=$(user) GROUP_ID=$(group) docker-compose
symfony := symfony
php := $(symfony) php
composer := $(symfony) composer

HELP += $(call help,setup,  Setup the development environment)
setup: setup-symfony build-docker
	$(dc) up --detach
	$(setup)

setup-symfony:
	$(symfony) server:ca:install
	$(symfony) proxy:start
	$(symfony) proxy:domain:attach {{ .Vars.system.app_name }}

build-docker:
	$(dc) pull && $(dc) build

HELP += $(call help,up,  Start the development environment)
up:
	$(dc) up --detach

HELP += $(call help,halt,  Stop the development environment)
halt:
	$(dc) down

HELP += $(call help,destroy,  Destroy the development environment)
destroy: halt
	$(dc) rm --force
