name: Manala Sync

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "A specific branch to target when fetching repository and committing changes"
        default: ""
        type: string
        required: false
      init:
        required: false
        description: Whether to run in init mode or not
        type: boolean
        default: false
      project:
        required: false
        description: Paired with init mode it define the project name to be used
        type: string
        default: null
  repository_dispatch:
    types: [synchronize]

env:
  TZ: UTC

jobs:
  synchronize:
    uses: Yproximite/actions/.github/workflows/manala_synchronize.yml@master
    with:
      default_branch: "${{ github.event.repository.default_branch }}"
      target_branch: "${{ github.event.client_payload.target_branch || github.event.inputs.target_branch }}"
      init: "${{ github.event.repository.init }}"
      project: "${{ github.event.repository.project }}"
    secrets:
      token: ${{ secrets.GH_MANALA_SYNC_TOKEN }}
