name: Manala Sync

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: "A specific branch to target when fetching repository and committing changes"
        default: ""
        type: string
        required: false
  repository_dispatch:
    types: [synchronize]

env:
  TZ: UTC

jobs:
  synchronize:
    uses: Yproximite/actions/.github/workflows/manala_synchronize.yml@master
    with:
      default_branch: "${{ github.event.repository.default_branch }}"
      target_branch: "${{ github.event.client_payload.target_branch || github.event.inputs.target_branch }}"
    secrets:
      token: ${{ secrets.GH_MANALA_SYNC_TOKEN }}
