{{- with .Vars.system -}}
.SILENT:

-include .manala/Makefile

define setup_before
	(cd var; mkcert '{{ .hostname | toYaml }}' '*.{{ .hostname | toYaml }}')
endef

define setup
	$(VAGRANT_MAKE) install-app
endef

###########
# Install #
###########

## Install application
install-app: composer-install init-db
install-app:
	bin/console cache:clear
	yarn install
	yarn dev

install-app@test: export APP_ENV=test
install-app@test: install-app

install-app@integration: export APP_ENV=test
install-app@integration:
	# Composer
	composer install --ansi --verbose --no-interaction --no-progress --prefer-dist --optimize-autoloader
	# Yarn
	yarn install --color=always --no-progress --frozen-lockfile
	yarn dev

	$(MAKE) init-db@integration

################
# Common tasks #
################

composer-install:
	composer install --verbose --no-interaction

init-db:
	bin/console doctrine:database:drop --force --if-exists --no-interaction
	bin/console doctrine:database:create --no-interaction
	bin/console doctrine:schema:update --force --no-interaction # to remove when we will use migrations
	# bin/console doctrine:migrations:migrate --no-interaction
	bin/console hautelook:fixtures:load --no-interaction

init-db@test: export APP_ENV=test
init-db@test: init-db

init-db@integration:
	bin/console doctrine:database:create --no-interaction
	bin/console doctrine:schema:update --force --no-interaction # to remove when we will use migrations
	# bin/console doctrine:migrations:migrate --no-interaction
	bin/console hautelook:fixtures:load --no-interaction

reload-db@test:
	APP_ENV=test bin/console hautelook:fixtures:load --purge-with-truncate --no-interaction

{{- end }}
