version: 2
registries:
    npm-registry-npm-fontawesome-com:
        type: npm-registry
        url: https://npm.fontawesome.com
        token: '${{secrets.NPM_REGISTRY_NPM_FONTAWESOME_COM_TOKEN}}'
    composer-repository-repo-packagist-com:
        type: composer-repository
        url: https://repo.packagist.com
        username: token
        password: '${{secrets.COMPOSER_REPOSITORY_REPO_PACKAGIST_COM_PASSWORD}}'
    npm-registry-npm-pkg-github-com:
        type: npm-registry
        url: https://npm.pkg.github.com
        token: '${{secrets.NPM_REGISTRY_NPM_PKG_GITHUB_COM_TOKEN}}'

updates:
    - package-ecosystem: composer
      directory: '/'
      schedule:
          interval: monthly
          time: '21:00'
          timezone: Europe/Paris
      open-pull-requests-limit: 5
      registries:
          - composer-repository-repo-packagist-com

    - package-ecosystem: npm
      directory: '/'
      schedule:
          interval: monthly
          time: '21:00'
          timezone: Europe/Paris
      open-pull-requests-limit: 5
      registries:
          - npm-registry-npm-fontawesome-com
          - npm-registry-npm-pkg-github-com

    - package-ecosystem: github-actions
      directory: '/'
      schedule:
          interval: weekly
