manala:
    description: yProximite - Sylius projects using Docker
    template: .manala.yaml.tmpl
    sync:
        - .manala/
        - .docker/
        - .github/workflows/ci.yml
        - .github/workflows/cd.yml.tmpl
        - .github/workflows/composer_operations.yml
        - .github/workflows/manala_sync.yml.tmpl
        - .dockerignore
        - docker-compose.yaml.tmpl
        - Procfile.tmpl
        - .env.example.tmpl

system:
    # @option {"label": "App name (in kebab-case)"}
    # @schema {"type": "string"}
    app_name: ~
    # @schema {"type": ["string"], "pattern": "^[a-zA-Z]+/[a-zA-Z]+$"}
    timezone: Etc/UTC
    php:
        # @schema {
        #     "items": {"type": "object",
        #         "additionalProperties": false,
        #         "properties": {
        #             "config": {"type": ["object", "string", "array"]}
        #         }
        #     }
        # }
        configs: []
    run:
        # @schema {"type": ["string", "null"]}
        postdeploy: ~
    mysql:
        # @option {"label": "MySQL version"}
        # @schema {"enum": [null, 5.7, 8, "8.0"]}
        version: ~
        # @schema {"type": ["string", "null"]}
        init: ~
    redis:
        # @option {"label": "Redis version"}
        # @schema {"enum": [null, "*"]}
        version: ~
        # @schema {"type": ["object", "array"]}
        config: {}
    elasticsearch:
        # @option {"label": "ElasticSearch version"}
        # @schema {"enum": [null, "6.8.22", "7.16.2"]}
        version: ~
        # @schema {"type": ["array"]}
        plugins: []
